logging:
  config: classpath:logback-spring.xml
  level:
    com.xc.fast_deploy: info
    executableSql: debug
arthas:
  agent-id: fast_deploy
  tunnel-server: 'ws://172.16.29.110:7777/ws'
mybatis:
  configuration:
    log-prefix: executableSql.
myself:
  pspass:
    harbor:
      uri: 134.108.3.248:8101
      account: oss_test
      password: OssborZJ!920
pagehelper:
  helper-dialect: mysql
  reasonable: true
  params: count=countSql
  support-methods-arguments: true
spring:
  application:
    name: deploy
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  profiles:
    active: test-bak
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 1024MB
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  #定义出现错误是直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
            threadPriority: 3
            threadsInheritContextClassLoaderOfInitializingThread: true