server:
  port: 8093
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      master:
        url: jdbc:mysql://134.108.6.246:8806/deploy?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&?zeroDateTimeBehavior=convertToNull&useSSL=false
        username: root
        password: Zdh!@adm_18
      slave:
        url: jdbc:mysql://134.108.1.149:8821/psotdata?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&?zeroDateTimeBehavior=convertToNull&useSSL=false
        username: zdhadmin
        password: Zdh!@adm_19
      initial-size: 5
      min-idle: 10
      max-active: 50
      max-wait: 600000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      poolPreparedStatements: true
jenkins:
  url: http://134.108.27.80:8001/jenkins/
  username: jellf
  password: jellf1q2w3e!@#$

arthas:
  agent-id: fast_deploy
  tunnel-server: 'ws://134.108.27.80:7777/ws'
logging:
  path: /app/fast_deploy_new/logs
file:
  storge:
    path:
      prefix: /data1/fast_deploy/
      uploadPath: /data1/fast_deploy/svn_module_excel/
      excelPath: /data1/fast_deploy/model_file/svn_module.xlsx
      modelPath: /data1/fast_deploy/model_file/model.zip
      moduleUploadPath: /data1/fast_deploy/upload_path/
      moduleExportPath: /data1/fast_deploy/export_path/
      deploySelfYamlPath: /data1/fast_deploy/deploy_self_yaml/
local:
  ipAddr: 134.108.27.80:8093
  #  port: 6001
netty:
  websocket:
    host: 0.0.0.0
    port: 6001
    bossLoopGroupThreads: 100
    workerLoopGroupThreads: 100
    optionSoBacklog: 128
    childOptionSoRcvbuf: 1024
    childOptionSoSndbuf: 1024
myself:
  httpUrl:
    getPermissionUrl: http://134.108.6.244:8000/multiauth/fast_deploy/listemid_roleid2/?empid=
    judgeIsLogin: http://134.108.6.244:8000/multiauth/Session_online/islogin/
    getNodeResources: http://134.108.6.244:8000/multiauth/K8s_monitor/listnode/?page=1&page_size=100&
    redirectLogin: http://134.108.6.244:8000/multiauth/Session_online/sso/?loginurl=http://134.108.27.80:8093/loginHtml
    loginUrl: http://134.108.27.80:8093/loginHtml
    logoutUrl: http://134.108.6.244:8000/multiauth/User/logout/
    loginIp: 134.108.6.244
    zdywCookeyKey: zdywpaassession
  pspass:
    prod: false
    ids: 4,10,19,25,26,27,29
    prodId: 25,22,45,46
    realprodid:
    oldversion: 22,24,25,26,27,30,32,33,35,36,37,38,39
    harbor:
      uri: 134.108.3.248:8101
      account: oss_test
      password: OssborZJ!920
  queue:
    size: 8
redisConfig:
  ip: 134.108.11.175
  port: 9054
  database: 0
  password: TEST_BSS_DEPLOY_001_USER#TEST_BSS_DEPLOY_001_USER123
  maxIdle: 30
  minIdle: 5
  maxTotal: 50
  MaxWaitMillis: 3000